### MASTER WORKFLOW (CBT-CI-CD-ALL)
name: Deploy Full Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy Node.js Backend
          repo: Bhavin2301/CBT-Backend
          token: ${{ secrets.GH_PAT }}

  trigger-frontend:
    runs-on: ubuntu-latest
    needs: trigger-backend
    steps:
      - name: Trigger Flutter Deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Flutter CI/CD
          repo: Bhavin2301/CBT_APP
          token: ${{ secrets.GH_PAT }}
